// <auto-generated />
using CaixaEletronicoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaixaEletronicoAPI.Migrations
{
    [DbContext(typeof(CaixaEletronicoAPIContext))]
    [Migration("20210731161438_tipoconta")]
    partial class tipoconta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("CaixaEletronicoAPI.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Agencia")
                        .HasColumnType("int");

                    b.Property<int>("FavorecidoId")
                        .HasColumnType("int");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoContaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FavorecidoId");

                    b.HasIndex("TipoContaId");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("CaixaEletronicoAPI.Models.Favorecido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Favorecido");
                });

            modelBuilder.Entity("CaixaEletronicoAPI.Models.TipoConta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoConta");
                });

            modelBuilder.Entity("CaixaEletronicoAPI.Models.Conta", b =>
                {
                    b.HasOne("CaixaEletronicoAPI.Models.Favorecido", "Favorecido")
                        .WithMany()
                        .HasForeignKey("FavorecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaixaEletronicoAPI.Models.TipoConta", "TipoConta")
                        .WithMany()
                        .HasForeignKey("TipoContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorecido");

                    b.Navigation("TipoConta");
                });
#pragma warning restore 612, 618
        }
    }
}
